# Use slim Python base
FROM python:3.10-slim

# Install system dependencies (includes libgomp for LightGBM)
RUN apt-get update && apt-get install -y libgomp1 && apt-get clean
RUN pip install mysql-connector-python

# Set working directory
WORKDIR /app

# Copy requirements and install
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Install boto3 explicitly if not in requirements.txt
RUN pip install --no-cache-dir boto3

# Copy app and folders
COPY app/ app/


# Set environment variable (optional, can help boto3 in some setups)
ENV AWS_DEFAULT_REGION=us-east-1

# Run FastAPI app
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
