global:
  scrape_interval: 15s  # Prometheus will scrape metrics every 15 seconds

scrape_configs:
  - job_name: "fastapi"
    metrics_path: /metrics
    static_configs:
      - targets: ["fastapi:8000"]
